trigger:
- main  # or your branch

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agents

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
